### ISSUE TITLE
rule XOR does not work as expected

### ISSUE THREAD

**Issue by mirgeam** [openwrt/firewall4#34]
set_xmark rule is emitted as if it was set_mark instead

The behavior of rule (XOR firewall mark ) is exactly the same as the behavior of the (Assing firewall mark ) rule.
A rule with the XOR mark shall carry over the already MARK of the packet and with it apply the XOR logic )

`config rule
	option name 'MARK 02'
	list proto 'icmp'
	option src 'wan'
	option target 'MARK'
	option set_mark '02'

config rule
	option name 'XOR_PING 01'
	option src 'wan'
	option proto 'icmp'
	option target 'MARK'
	option set_xmark '01'

config rule
	option name 'Allow_ping_mark 03'
	list proto 'icmp'
	option src 'wan'
	option target 'ACCEPT'
	option mark '03'

`

The resutin xor rule is:
meta l4proto { icmp, ipv6-icmp } iifname "eth0" meta mark 0x00000001 counter packets 0 bytes 0  meta mark set 0x00000001 comment "!fw4: XOR"
	}

The expected result shall look like this:
meta l4proto { icmp, ipv6-icmp } iifname "eth0" counter packets 0 bytes 0  meta mark set meta mark xor 0x00000001 comment "!fw4: XOR_PING"
    }

**Comment by jow-** [comment]
The current behavior is supposed to mirror `iptables-translate` logic:
```
iptables-translate -A INPUT -j MARK --set-xmark 01
nft 'add rule ip filter INPUT counter meta mark set 0x1'
```

To achieve desired behavior, you need to supply a zero mask (to override the implicit 0xfffffff assumption):
```
iptables-translate -A INPUT -j MARK --set-xmark 01/00
nft 'add rule ip filter INPUT counter meta mark set mark xor 0x1'
```

While this may seem counter-intuitive, this is supposed to exactly mirror iptables logic in order to tay backwards-compatible with existing configs.

**Comment by brada4** [comment]
The testcase illustrates it default mask is `(f)` and total is opptimized to `or` done over zeroes 
https://git.netfilter.org/iptables/tree/extensions/libxt_MARK.txlate#n7

**Comment by brada4** [comment]
Destructive-by-default behaviour confirmed on centos7 ((iptables 1.4.21-35), likely you went to a place nobody walked before.

**Comment by mirgeam** [comment]
Yes, using the XOR in that way the results are as expected.


option set_xmark 01/00
